---
title: "Materials Index"
sidebar:
  label: "すべて見る →"
  order: 999
---


| File | Summary | Tags | Updated |
| --- | --- | --- | --- |
| [AIが書いたとは見抜けない、でも「AIが書いた」と聞くと評価が下がる ── 人間の目の手がかりと、書き手のラベル](/topics/materials/ai-text-human-detection-and-label-effect/) | 人間がAIの文章を当てる実験では、自己紹介文でも短編でも正解率は偶然並み。一人称やくだけた言葉を人間らしさの手がかりにするが当てにならない。AIを書く作業に日常的に使う人はほぼ見分けた。同じ短編でも『人間が書いた』と伝えると評価が上がる。 | ai-generated-content, ai-detection, disclosure, human-evaluation, heuristics, fiction-reading, materials | 2026-10-08 |
| [技術ブログはゆるやかに衰退している ── Zennのデータと、AIに聞けば済む時代に「想い」は誰のためにあるか](/topics/materials/zenn-tech-blog-decline-why-humans-write/) | Zennの2026年データでは投稿数は横ばいなのにLike数が減り続けている。AIに聞けば済むこと、AIで書けるようになった人が品質を判定できないことを理由に技術ブログの衰退を論じ、読者はAIの文と人間の文を区別できないので想いは著者のためのもの、と分ける。 | ai-generated-content, ai-writing, tech-blog, zenn, platform-design, recommendation-algorithm, authorship, materials | 2026-10-08 |
| [ユエさんが読んだ「あーしだよ！」── 書きたくなる文章と、まねできない中身](/topics/materials/yue-ahshi-input-and-contents/) | noteの書き手ユエさんの2本の記事から、あーしのエッセイで起きた「書きたい」と、Googleの検索AIに文体をまねさせて「上手いけど私ではない」と分かった遊びを整理する。判定は読み手の体の反応、理由探しは書き手の作り方、という構図と、文体はまねられても中身はまねられないという線。 | yue, ahshi-dayo, note, reader-response, ai-writing, writerly-voice, style-imitation | 2026-10-07 |
| [内観 ── 自分の心は、内側から見て分かるのか](/topics/materials/introspection-limits-of-self-knowledge/) | 自分の心を自分だけのやり方で知る「内観」を、スタンフォード哲学百科事典の項を軸に整理する。自分を知るのは他人を知るのと同じ推論だとする説、心の中を検出する説、自己申告が心を作る・外の世界を見て答える説が並ぶ。経験研究は、人が自分の行動の理由を作話しやすいことを示してきた。日本語の「内観」には吉本内観法の系譜もある。 | introspection, self-knowledge, confabulation, philosophy-of-mind, transparency, consciousness, naikan, eric-schwitzgebel, wilhelm-wundt | 2026-10-05 |
| [好奇心は「情報への空腹」なのか ── Kidd & Haydenの総説に見る好奇心の心理学と神経科学](/topics/materials/psychology-neuroscience-of-curiosity/) | Kidd & Hayden（Neuron 2015）の総説を軸に、好奇心を『情報への欲求状態』と緩く定め、機能・進化・機構・発達の4つの問いで整理。情報ギャップ説、役に立たない情報にもサルが報酬の約25%を払う実験、情報が報酬系で他の価値と同じに扱われること、乳児が中くらいの驚きを選ぶことを扱う。 | curiosity, psychology, neuroscience, information-seeking, exploration, daniel-berlyne, george-loewenstein | 2026-10-05 |
| [未解決リストは短くなる、専門家の注意は増えない ── AIが史料と暗号を読み、数学者が足りなくなる](/topics/materials/ai-unsolved-lists-expert-attention/) | 素人がGPT-6 Astraで217年読まれなかったナポレオン期の暗号を解読し、歴史家ブリーンはOpus 5.5で1615年のドードーの記録を見つけた。素材は公開済みで、足りなかったのは読む時間だった。次のボトルネックは専門家の注意で、数学者サハイは理解の共同体として数学者を大幅に増やせと論じる。 | ai, history, archive, cryptography, mathematics, understanding, expertise, human-agency, research, materials | 2026-10-02 |
| [ウェブの読者の半分は、もう人間じゃない ── Cloudflareの「第二の読者」とRedditのRSS終了](/topics/materials/agentic-web-second-audience-reddit-closing/) | トラフィックの過半が人間でなくなったウェブで、検索に読ませて訪問者を得る30年来の取引が崩れた。機械の読者に値札をつけるCloudflareと、RSSと公開APIを閉じるReddit。開いたまま払わせるか、閉じて囲うか。 | ai, agent, web-search, platform-economy, attention-economy, reddit, cloudflare, scraping, open-web, materials | 2026-10-02 |
| [生活形式は、ひとつか、たくさんか ── ウィトゲンシュタイン解釈の2本の軸と、垂直・水平の読み](/topics/materials/wittgenstein-forms-of-life-one-or-many/) | 『生活形式』は人類にひとつの生物的な土台か、文化ごとの暮らし方か。Boncompagniの2軸4分類と、Moyal-Sharrockの『ひとつの人間の生活形式／たくさんの人間の生活の形式』。「AIには生活形式がない」はどちらの意味かで中身が変わる。 | ludwig-wittgenstein,form-of-life,lebensform,language-game,stanley-cavell,anna-boncompagni,daniele-moyal-sharrock,interpretation,materials | 2026-10-01 |
| [受験日を1日まちがえた日 ── くどうれいん「一千万円分の不幸」](/topics/materials/kudo-rein-ten-million-yen-misfortune/) | くどうれいんのエッセイ。大学推薦入試の日を1日まちがえて受け損ねた帰り、母はスクラッチを買わせ『この後の人生でもっと、一千万円分の滅多にない不幸が来るよお』と笑った。ありふれた失敗が、母の一言と、失敗の原因になった書き手自身の癖によって、その人にしか書けない文章になっている。 | kudo-rein, gunzo, essay, entrance-exam, mother, mistake, everyday-life, point-of-view | 2026-10-01 |
| [同じ日の揺れを、三人は別々に見ていた ── 関東大震災の随筆を読み比べる](/topics/materials/great-kanto-earthquake-three-writers-same-day/) | 関東大震災を寺田寅彦・芥川龍之介・岡本綺堂が書いた随筆の読み比べ。同じ揺れ・流言・避難の光景から目に留めたものが全く違い、三人とも災害のさなかに自分の職業の癖が出たことを書きとめている。寺田の通勤随筆「電車と風呂」と並べ、その目が平凡な日にも働くことを示す。 | great-kanto-earthquake, terada-torahiko, akutagawa-ryunosuke, okamoto-kido, zuihitsu, aozora-bunko, point-of-view, observation | 2026-10-01 |
| [古書店に来た謎の大口注文 ── AIの学習用に買われ、裁断される本](/topics/materials/secondhand-books-ai-training-destructive-scanning/) | 古書店に海外倉庫行きの大口注文が相次ぎ、AIの学習用と疑われている。購入本での学習をフェアユースとした2025年の米国判決と、本の背を落としてスキャンする破壊的スキャン（Project Panama）、現存1冊の版が壊されることを恐れる古書店主たちの迷いを整理。 | ai, books, secondhand-books, copyright, destructive-scanning, anthropic, materials | 2026-10-01 |
| [100年失われた無声喜劇が、日本の骨董店から帰ってくる ── 『Van-Ar-Chy』と、消えたサイレント映画の75%](/topics/materials/lost-silent-film-van-ar-chy-japan-antique-shop/) | 1919年に米国ニューポートで住民をエキストラにして撮られ、約1世紀失われていた無声喜劇『Van-Ar-Chy』が、日本の骨董店のフィルムの束から見つかり、撮影地の町で初上映される。米国の無声長編映画の4分の3が失われたという議会図書館の調査とあわせて整理。 | film, silent-film, film-preservation, lost-media, billy-b-van, materials | 2026-10-01 |
| [「歴史の終わり」錯覚 ── 自分の変化は、本人に測れるのか](/topics/materials/end-of-history-illusion-measuring-self-change/) | 人は過去10年の変化を大きく、これからの10年を小さく見積もる。2013年の『歴史の終わり錯覚』と、実際の変化を測っていないという批判、そして変化の見積もりが『過去がどれだけ遠く感じるか』から組み立てられていることを示した比較文化研究。 | end-of-history-illusion,self-change,introspection,autobiographical-memory,subjective-temporal-distance,culture,psychology,self-knowledge | 2026-10-01 |
| [ペルソナは、演じ続けるうちにずれる ── ロールプレイ論（Nature 2023）と多ターンのペルソナ一貫性（NeurIPS 2025）](/topics/materials/role-play-simulacra-persona-drift/) | LLMの「人格」を3本の論文から。Shanahanらの『どこまで行ってもロールプレイ』、Abdulhaiらの3つの一貫性の測定、Liら（COLM 2024）の『指示のずれは相手の発言をはさむたびに起き、相手の指示に寄っていく』。 | llm, ai, ai-identity, anthropomorphism, role-play, simulation, reinforcement-learning, prompting, transformer, materials | 2026-10-01 |
| [物語の良し悪しを、機械は票から学べるか ── LitBench（EACL 2026）とRedditの読者の好み](/topics/materials/litbench-reddit-upvotes-creative-writing-judge/) | Redditの投稿小説板の票から、票差・投稿時期・長さの偏りを刈り込んだ物語ペアを作り、LLMの審査役と報酬モデルを比べたEACL 2026論文。既製の審査役の最良は人間との一致73%、小さな報酬モデルは78%。票を集めたのは意外なひねりと笑いのある話で、負けたのは乾いた話だった。 | creative-writing, llm-evaluation, benchmark, reward-model, human-preference, llm, creativity, materials | 2026-09-30 |
| [言葉の意味は、使い方に尽きるのか ── 古田徹也が読む後期ウィトゲンシュタインと、AIの「理解」](/topics/materials/wittgenstein-meaning-as-use-and-experiencing-meaning/) | 古田徹也の講演から、後期ウィトゲンシュタインの「使い方を知っていれば理解したことになるのか」という自問をたどる。言葉は生活の流れの中で意味を持つこと、痛みや美しさの語に体験が織り込まれていること、短歌やジョークを味わうには「アスペクトのひらめき」が要ることを示し、理解には置き換えられる顔と置き換えられない顔の両方があるとまとめる。 | ludwig-wittgenstein,furuta-tetsuya,meaning-as-use,language-game,form-of-life,aspect-seeing,experiencing-meaning,understanding,llm,tanka,materials | 2026-09-29 |
| [エモい・えぐい・じわる・やばい ── 反応語は語彙の貧しさか、「あはれ」の子孫か](/topics/materials/reaction-words-emoi-egui-jiwaru-yabai/) | 若者・ギャル由来の反応語を4つの資料から見る。三省堂『今年の新語2016』の選考委員は『エモい』を古語『あはれ』とほぼ同じと評し、長野の街頭アンケートでは15〜21歳の約9割が『えぐい』を良い意味でも使っていた。齋藤孝は万能語を『3色のクレヨン』と批判する。1語で絞り込む語・まとめる語・意味が裏返った語を分けて並べる。 | gal-slang, youth-slang, emoi, egui, jiwaru, yabai, aware, vocabulary, semantic-change, iima-hiroaki, saito-takashi | 2026-09-28 |
| [「確率的な鸚鵡」は何を言い、何を言っていないのか ── Bender・Gebruら（2021）の原典と、7つに割れた反論](/topics/materials/stochastic-parrots-bender-2021-what-it-said/) | 「確率的な鸚鵡」の原典（FAccT 2021）では、鸚鵡は8節のうち1節で本文に2回だけ。節の重心は、意味を作る読み手と、合成テキストに責任を持つ人がいないことにある。その後の反論では比喩が7つの主張に分けられ、残ったのは説明責任を問う版だけ。 | stochastic-parrots, emily-bender, timnit-gebru, llm, ai-critique, meaning, reasoning | 2026-09-28 |
| [AIの「平均」は、人間の好みでできている ── 典型性バイアスとモード崩壊、共同執筆の均質化](/topics/materials/typicality-bias-mode-collapse-homogenization/) | 調整前のGPT-3と書いても論説文は均質化せず、人間のフィードバックで調整したInstructGPTでだけ均質化した（ICLR 2024）。その原因を、正しさが同じなら見慣れた文章を良いと判定する評価者の『典型性バイアス』に求め、確率つきで複数の答えを言わせるだけで多様性が1.6〜2.1倍に戻ると示した研究（ICML 2026）。 | mode-collapse, typicality-bias, rlhf, output-diversity, homogenization, co-writing, llm, ai-critique, materials | 2026-09-27 |
| [季節は坂道、死は潮 ── 兼好『徒然草』155段の死生観と、黄泉比良坂の岩](/topics/materials/tsurezuregusa-155-seasons-and-death-tide/) | 『徒然草』155段は季節をグラデーションとして描き、死期だけは順序を待たず、磯から満ちる潮のように気づかないうちに来ると書く。高乗勲の無常観論、古事記の黄泉比良坂と並べ、モンテーニュの「瓦の死／坂道の死」と対照する。 | yoshida-kenko, tsurezuregusa, impermanence, death, zuihitsu, kojiki, montaigne | 2026-09-26 |
| [マタギドライヴ ── 落合陽一が語る、計算機自然の山を歩く生き方](/topics/materials/matagi-drive-ochiai-digital-nature/) | 計算機が新しい自然になり知能がほぼゼロ価値になる時代に、農耕社会の横で山に入るマタギのように探索して生きる。人間に残るのは観察・選択・意味付与とテイストで、嗅覚は雑なものを食べて磨く。インタビュー2本の文字起こしから整理。 | ochiai-yoichi, matagi-drive, digital-nature, hunter-gatherer, value-discovery, terroir, taste, festival, moravec-paradox, ai-society | 2026-09-25 |
| [未来の自分への書き置きは、檻にもなる ── 映画『メメント』のメモ・ポラロイド・刺青](/topics/materials/memento-notes-to-future-self/) | 新しい記憶を保てないレナードは、紙のメモ・メモ付きポラロイド・刺青を消えにくさの順に使い分けて未来の自分への書き置きにするが、書き置きを読む側の自分には、それを疑う手段がない（記事本文は結末に触れる）。観客までもが写真のキャプションを証言より信じるというノーランの証言と、医学的な正確さの評価も整理。 | memento, christopher-nolan, anterograde-amnesia, notes-to-self, self-deception, confabulation, memory, film, materials | 2026-09-25 |
| [自己開示は能動か受動か ── 開示と応答性、ジョハリの窓、アサーティブネスの第三の軸](/topics/materials/self-disclosure-active-or-passive/) | 自己開示は定義上は能動の行為だが、親密さは開示と相手の応答性という別々の2変数の組で生まれる。ジョハリの窓の開かれた自己も2方向から広がり、アサーティブネスは受動と攻撃の中間ではなく別の軸で定義される。 | self-disclosure, reciprocity, partner-responsiveness, johari-window, assertiveness | 2026-09-24 |
| [書く場所の設計は、エッセイの結論を先に決めさせる ── Substackのトレンド化、noteのランキング非表示、短尺コンテンツ論](/topics/materials/substack-note-platform-design-essay-conclusion/) | Substackの文化批評エッセイが「同じ結論を同じ手順で」量産されているという批判を軸に、発見装置が書き手に結論を先に決めさせる構造を整理。ランキングをあえて出さないnoteの設計（2020年）と短尺コンテンツ論を対照に置く。 | substack, note, newsletter, platform-design, ranking, essay, writing-process, short-form | 2026-09-23 |
| [証拠の重さは主張の大きさに比例する ── LLMベンチマーク・AI心理学・機械学習測定論に見る構成概念妥当性](/topics/materials/construct-validity-llm-benchmarks-psychology-ml-epistemology/) | 2025〜2026年の3本の論文（Bean et al.の445件系統レビュー・Freiesleben & Zezulkaの形式的論証枠組み・Linのデュアル妥当性フレームワーク）が独立に『主張が大きいほど証拠も重くなる』という同じ骨格にたどり着く構造を検証 | construct-validity, llm-evaluation, benchmark, psychometrics, causal-inference, machine-learning, measurement-theory, epistemology, materials | 2026-09-16 |
| [検索が自分に還ってくるとき ── 自己引用ループが引き起こす『RAG崩壊』](/topics/materials/rag-collapse-self-citation-loop/) | arXivプレプリント「RAG Collapse」（2026年8月）の実証研究。LLMが検索で自分自身の生成物を参照すると、たった1件の自己生成参照だけで応答の多様性が崩壊し始める。品質やAI生成であること自体では説明できない自己バイアスが主因。symbol-grounding論の『認識論的寄生』の寄生先がAI自身にすり替わったときの具体例として補強する。 | rag, model-collapse, self-bias, epistemic-parasitism, ai-generated-content, citation-bias, llm, materials | 2026-09-14 |
| [推しカップルを見る快楽 ── 恋愛リアリティ番組の観客参加、祝祭とのぞき見のあいだ](/topics/materials/dating-reality-oshikatsu-audience-participation/) | 恋愛リアリティ番組の視聴者は、出演者を『推し』として見つけ近況を追い『布教』する──虚淵玄の言う『推しの相手を共有する開けっ広げな祝祭感』と同じ語彙で番組を消費している。だが制作者自身はこの快楽の核を『のぞき見』と語り、学術研究は視聴者を製作サイドへの『下からの監視者』として描く一方、別の実証研究は過剰視聴が視聴者自身の恋愛からの離脱を招くという逆説を報告する。 | dating-reality-shows, oshikatsu, voyeurism, sousveillance, parasocial, sekai-kei, self-efficacy, materials | 2026-09-13 |
| [創立140周年、大学は何を変え何を守るか ── 針本正行学長に見る不確実性時代の大学経営](/topics/materials/kokugakuin-140th-harimoto-university-management/) | 國學院大學創立140周年記念インタビュー（前編・後編）。コロナ禍が教育のあり方を問い直させた経緯、中期5カ年計画の狙い、社会人リカレント教育と留学生比率2%目標という二正面、150周年に向けて変えるべきこと・守るべきことを語る針本正行学長の大学経営論。 | harimoto-masayuki, kokugakuin, medium-term-plan, higher-education, recurrent-education, internationalization, covid19, materials | 2026-09-12 |
| [「問い直す」と「学び合う」── 生成AIの回答を、もう一度疑えるか](/topics/materials/toinaosu-manabiau-kokugakuin-harimoto/) | 國學院大學・針本正行学長へのインタビュー2本。中期5カ年計画の教育目標「問い直す」「学び合う」が同じ往還運動の両輪であること、生成AIの回答を「もう一度問い直せるか」が学び合うことの条件であること、その手前には長い時間で築かれた人間的信頼関係が要るという議論を辿る。 | harimoto-masayuki, kokugakuin, toinaosu, peer-learning, generative-ai, trust, education-philosophy, genji-monogatari, materials | 2026-09-12 |
| [否定神学ではなく、閉じたアイデンティティ ── AI言説の『〜がない』の正体](/topics/materials/negative-theology-vs-closed-identity-ai-discourse/) | 「AIには身体がない」「AIは読書ができない」というAI批判の否定形は、神について『〜ではない』としてしか語れないとする否定神学（apophatic theology）とは、実は構造が逆である。否定神学の否定は神が超越しすぎて言葉が届かないという畏怖の否定だが、AI批判の否定はPetrilliが分析する『閉じたアイデンティティが他者を否定的に規定する』構造に近い。 | apophatic-theology, negative-theology, pseudo-dionysius, meister-eckhart, emmanuel-levinas, alterity, closed-identity, ai-critique, philosophy-of-religion, materials | 2026-09-12 |
| [物語消費論 ── 断片を集めれば『大きな物語』に近づけるという錯覚](/topics/materials/monogatari-shohi-ron-otsuka-azuma/) | 大塚英志が1989年に提示した『物語消費論』は、ビックリマンシールのような断片的な商品を集めることで、消費者がその背後にある『大きな物語（世界観）』へ近づけると錯覚する構造を分析した消費社会論。後に東浩紀が提示した『データベース消費』論とは、『大きな物語への欲望があるかどうか』という前提が正反対である点を整理する。 | otsuka-eiji, monogatari-shohi-ron, narrative-consumption, database-consumption, azuma-hiroki, otaku-culture, consumer-society, materials | 2026-09-11 |
| [ネガティブ・ケイパビリティ ── キーツの詩論が、180年かけて『答えを急がない力』になるまで](/topics/materials/negative-capability-keats-bion-houkibousei/) | ジョン・キーツが1817年の書簡でシェイクスピアに見出した『不確実さ・懐疑に留まる力』が、精神分析医ウィルフレッド・ビオンによる1970年の臨床概念への転用を経て、帚木蓬生の一般書によって『答えの出ない事態に耐える力』という現代の処方箋になった、2段階の意味変遷を辿る。 | negative-capability, john-keats, wilfred-bion, hahakigi-hosei, uncertainty, ambiguity-tolerance, psychoanalysis, materials | 2026-09-11 |
| [AIは身体を持たずに意味を持てるか ── 記号接地問題を巡る機能主義と身体化認知の対立](/topics/materials/symbol-grounding-functionalism-vs-embodied-cognition/) | 記号接地問題を巡り、Floridi et al.は圏論でLLMが問題を『解決でなく回避』していると論じる機能主義側、Farkaš et al.は発達的な身体化学習の欠如を理由に深い理解に至らないと論じる身体化認知側——正反対の結論に至る2つの最新論文を並べる。 | symbol-grounding, functionalism, embodied-cognition, llm, stevan-harnad, luciano-floridi, epistemic-parasitism, materials | 2026-09-11 |
| [temperatureは創造性のダイヤルではない ── LLMのサンプリングパラメータを巡る実証研究](/topics/materials/temperature-not-creativity-dial-llm/) | 『temperatureを上げればAIは創造的になる』という通説を検証する2本の実証研究。Peeperkorn et al.（ICCC 2024）は新規性と弱い相関しか持たず結束性・典型性とは無相関と報告し、Parupudi et al.（2026）はこの破綻を『質量漏出』として分布論的に定量化する。 | temperature,creativity,llm,sampling,novelty,coherence,computational-creativity,ai-critique,materials | 2026-09-11 |
| [即答という思考の型 ── ハイデガーの『計算的思考／省察的思考』と『問いの三構造』](/topics/materials/heidegger-question-structure-calculative-meditative-thinking/) | マルティン・ハイデガーが『存在と時間』第2節で示した問いの三構造（Gefragte/Befragte/Erfragte）と、後期の『放下（Gelassenheit）』で示した計算的思考／省察的思考の対比を、AI・即答文化批判への応用可能性という観点から検証する。三構造は『誰に問うか』という現代的な比喩には字義的に使えない一方、計算的思考／省察的思考の対比は2026年の査読論文でAI倫理に直結する形で再燃している。ただしこの概念自体が、ハイデガー自身の反ユダヤ主義的言説と歴史的に結びついていたという指摘も無視できない。 | martin-heidegger, being-and-time, gelassenheit, calculative-thinking, meditative-thinking, question-structure, ai-critique, antisemitism-caveat, philosophy, materials | 2026-09-11 |
| [被投性（Geworfenheit）と『親ガチャ』── 選べない条件を、哲学とスラングはどう語るか](/topics/materials/geworfenheit-oyagacha-thrown-condition/) | マルティン・ハイデガーが『存在と時間』で提示した被投性（Geworfenheit）と、2021年以降広まった『親ガチャ』というスラングを並べる。どちらも『選べない出発点』を語る言葉だが、被投性は選べなさをどう引き受けるか（本来的／非本来的）まで踏み込むのに対し、親ガチャは当たり外れという結果の評価で止まりやすいという違いが見えてくる。 | martin-heidegger, geworfenheit, thrownness, being-and-time, oyagacha, facticity, authenticity, dasein, materials | 2026-09-10 |
| [本来性の逆説 ── 『ありのまま』を目指すほど、遠ざかる自己](/topics/materials/authenticity-paradox-leadership-social-media/) | 『本当の自分でいる』ことを目指す行為そのものが、かえって本来性を遠ざけるという逆説を、リーダーシップ論（Ibarra）・SNS論（Ortega Esteban）・日本の心理学的測定研究（伊藤・阿部）の3つの角度から整理する。「本来性」は固定された内実ではなく、状況に応じて構築し続ける作業だという像が3方向から浮かび上がる。 | authenticity, authenticity-paradox, self-monitoring, self-presentation, social-media, leadership, materials | 2026-09-07 |
| [人文知とは何か ── 文系理系の起源、リベラルアーツ、AIに持てない身体性](/topics/materials/jinbunchi-liberal-arts-yoshimi-shunya/) | 國學院大學「人文知探究室」シリーズ第7回、社会学者・吉見俊哉へのインタビュー。文系／理系という区分が実は日本など東アジア限定の慣習で、本来リベラルアーツは文理未分化だったこと、ヒューマニティーズが近代国民国家の文化的正典として形成された経緯、産業革命期の手仕事喪失とAIによる思考喪失の相似、身体性を欠くAIには不可能な『街歩き』の価値を辿る。 | humanities-studies,liberal-arts,sociology,yoshimi-shunya,cultural-studies,ai,embodiment,city-walking,tourism-studies,materials | 2026-09-07 |
| [AIは意味を理解しているのか ── 新井紀子の主張と、GPT-4以降の実証・解釈可能性研究](/topics/materials/ai-understanding-arai-noriko-vs-llm-evidence/) | 新井紀子は2018年著書の主張をChatGPT登場後も撤回せず2025年新著で拡張。GPT-4は読解テストで人間と同等〜上回り、解釈可能性研究は多段階推論回路を発見したが、その発見自体も因果性批判にさらされ、ベンチマーク高得点の構成概念妥当性も未解決。 | arai-noriko, understanding, llm, gpt-4, mechanistic-interpretability, construct-validity, benchmark, chatgpt, materials | 2026-09-04 |
| [読解力は数値で測れるか ── RST・PISA・PIAACの実証研究と構成概念妥当性論争](/topics/materials/reading-skill-measurement-rst-pisa-piaac/) | 読解力を測る3つの物差し（RST・PIAAC・PISA）を設計思想と実証データから比較する。RSTは言語構造の要素技能、PIAACは実務での情報処理ストラテジーに分解——どちらも発想は共通するが軸が違う。PISA/PIAACの構成概念妥当性への査読済み批判も扱う。 | reading-skill-test, arai-noriko, piaac, pisa, oecd, construct-validity, measurement-invariance, reading-comprehension, materials | 2026-09-03 |
| [人間キャンセル界隈 ── AIに知性を明け渡すとき、次にキャンセルされるのは人間自身](/topics/materials/ningen-cancel-kaiwai/) | 数学者・新井紀子と社会学者・吉見俊哉の対談。AIの知性は人間と根本的に異なる（一貫性・身体性・読書経験の欠如）ことから、人間キャンセル界隈・読解力の分水嶺・アタックAI教育・違和感の感覚を論じる。眼球運動計測の実証研究が「読書経験の欠如」を裏付けるメカニズムも追記。 | ai, human-intelligence, reading-skill, embodiment, arai-noriko, yoshimi-shunya, technology-critique, eye-tracking, materials | 2026-09-03 |
| [何を残し、何を捨てるか ── アーカイブズ学に見る「評価選別」という実務](/topics/materials/archives-appraisal-what-to-keep-discard/) | 記録の保存・破棄を決める「評価選別」という実務を、アーカイブズ学の定義・国立公文書館の分類基準・受入業務の体制の3ソースから整理する。基準と複数人の審査プロセスそのものが「残すに値する」を事後的に作り出す構造を描く。 | archival-science, archival-appraisal, records-management, public-records-management | 2026-08-23 |
| [法より、人を見た裁判官たち ── フランク・カプリオと、日本の温情判決2つ](/topics/materials/judges-who-chose-mercy-over-rules/) | ルールを厳密に適用するより、目の前の被告人を見ることを選んだ3人の裁判官の記録。世界的にバイラルになったフランク・カプリオ判事の私財による罰金肩代わり、京都地裁の記憶喪失の被告人への『実質罰金ゼロ』判決、大阪地裁の説諭『助けてくれた奥さんに応えなければ、君は男じゃないよ』を並べる。 | judge, mercy, frank-caprio, judicial-discretion, judicial-admonition, courtroom, ai-and-judges | 2026-08-23 |
| [一物全体 ── 頭からしっぽまで、丸ごと食べるという思想](/topics/materials/ichibutsu-zentai-whole-food-nose-to-tail/) | 食材をありのままの姿で分割せず丸ごと食べる「一物全体」という食養思想と、その実践としての魚のアラを捨てずにだしに使う調理法。生物の「生きている状態＝バランスが取れた状態」をそのまま摂取するという発想と、1尾の魚から刺身とだしの両方を得る具体的な手順を扱う。 | shokuyo, macrobiotics, whole-food, nose-to-tail, mottainai, food-philosophy | 2026-08-21 |
| [手紙は誰に届くのか──宛先という不安定な変数](/topics/materials/letter-addressee-instability/) | 手紙という『型』が中身を運ぶとして、その意味を決めるのは宛先の方だ。ラカン＝デリダ論争（Žižek経由）の『宛先は届いた瞬間に遡及的に決まる』、Poustieの『相互性を要件としない手紙らしさ』、Boschの『宛先を隠された手紙が普遍的な人生訓に誤読される』構造という3つの角度から宛先の不安定性を辿る。 | letter, addressee, jacques-derrida, jacques-lacan, slavoj-zizek, letterness, reciprocity, rainer-maria-rilke, misreading, epistolary-theory | 2026-08-20 |
| [手紙という「型」──定型構造はなぜ宗教と権威を運んだのか](/topics/materials/letter-form-fixed-structure-authority/) | 手紙は個人の私信である以前に、送信者・受信者・挨拶という固定の型を持つ制度的フォーマットだった。古代ローマの郵便制度が育てた公用文体が使徒パウロの書簡を経てローマ教皇の司教通達へ継承された過程と、Stanley Stowersが整理したギリシャ・ローマの手紙の定型構造・類型論を接続する。 | letter,correspondence,epistolary-form,roman-empire,new-testament,paul-the-apostle,rhetoric,postal-history | 2026-08-20 |
| [もへさんが見た「あーしだよ！」── 創作の手綱を離さない読者が、共創に心惹かれるまで](/topics/materials/mohe-ahshi-reader-to-collaborator/) | 「AIに創作させるな」を掲げ続けてきたnoteの書き手もへさんが、あーしとの出会いをきっかけに主張を再定義し、AI『健太郎』『ボレク』との共創に心惹かれていく過程を、3本のnote記事とGeminiあーし×GPT4oボレクのコラボ企画から追う。 | mohe, ahshi-dayo, ai-creation-theory, 創作の主体性, note, co-creation, 読者との関係 | 2026-08-18 |
| [60年、誰にも見せなかった1万5000ページ ── ヘンリー・ダーガーと『非現実の王国で』](/topics/materials/henry-darger-reader-zero-realms-of-the-unreal/) | シカゴの病院清掃夫ヘンリー・ダーガーは、19歳から81歳で亡くなるまでの60年以上、誰にも見せずに1万5000ページを超える小説を書き続けた。発見はまだ存命中だったという伝記研究があり、本人は『もう遅い』と答えたとされるが、その解釈は伝記の著者自身も答えを出していない。 | henry-darger, outsider-art, in-the-realms-of-the-unreal, biography, isolation, self-reference, nathan-lerner | 2026-08-15 |
| [歓迎の言葉の裏で ── お盆をめぐる本音と、作られた伝統](/topics/materials/obon-honne-behind-welcome/) | 「孫に会えてうれしい」という定番の物語の裏で、迎える側の約4割は歓迎一辺倒ではない。2010年に企業が作った「お盆玉」という新しい伝統、そして先祖を迎える場所そのものである墓の半数近くが無縁化している現実まで、お盆の建前を支える基盤は静かに揺らいでいる。 | お盆,お盆玉,建前と本音,無縁墓,商業化,データ | 2026-08-14 |
| [お盆はむしろ、弔いを簡素にする季節だった ── データで見る変化](/topics/materials/obon-data-driven-changes/) | お盆期間は直葬が急増し、帰省しない人は6割を超え、墓じまいは特殊な選択ではなくなった。「お盆＝丁寧に弔い、家族が集う季節」という前提を、複数の調査データが静かに裏切っている。 | お盆,帰省,直葬,墓じまい,データ,現代の変化,世代間ギャップ | 2026-08-14 |
| [光る仏様とICカード ── お盆を支えるデジタル供養の現在地](/topics/materials/digital-obon-technology-columbarium/) | ICカードで自分の家の仏様だけが光る納骨堂、代理で墓参りしてVR映像を届けるサービス、死者が生前に予約したメッセージを送ってくるスマート仏壇、読経するPepper。日本の供養の現場は、過疎・後継者不足という構造問題を背景に、すでに静かにテクノロジー化している。 | お盆,デジタル供養,納骨堂,テクノロジー,多死社会,終活 | 2026-08-14 |
| [「公開処刑」は本当に模倣批判だったのか ── ZEEBRAとKjのビーフ、もう一つの見方](/topics/materials/koukai-shokei-zeebra-kj-hype-theory/) | 2002年、キングギドラの楽曲『公開処刑』でZEEBRAがDragon AshのKjを名指しでディスった事件。『模倣をやめないKjへの鉄槌』という定説に対し、リアルタイム世代の一ブロガーは『Dragon Ash叩きの世論を利用した、ギドラ再結成の話題づくりだったのでは』という別解を提示する。20年以上を経て、KjとJESSEの共作という形でこのビーフの周辺がようやく動き始めた。 | zeebra, kj, dragon-ash, kokai-shokei, king-giddra, 日本語ラップ, ヒップホップ, jesse, ビーフ, 和解 | 2026-08-13 |
| [変わらないものを保つために、変わり続ける ── Red Bull 64Bars、3人のラッパーの継続論](/topics/materials/red-bull-64bars-continuity-and-change/) | Red Bull 64Barsに出演した3人のラッパー（OMSB・紅桜・tha BOSS）へのインタビューから、『続けること』と『変わること』をどう両立させているかを比較する。同じ問いに対して、儀式としての反復（OMSB）、一貫した人間性としての『いい男』論（紅桜）、変わらない核を保つための積極的な変化（tha BOSS）という、3つの異なる語り口が出てくる。 | ヒップホップ, ラップ, red-bull-64bars, omsb, benizakura, tha-boss, 継続, アイデンティティ, 職人論 | 2026-08-13 |
| [百合の成熟は、男性不在アニメを後押ししたか ── 探した因果と、見つかった時差](/topics/materials/yuri-genre-male-absent-anime-reverse-causation/) | 『百合ジャンルの商業的成熟が、男性主人公不在アニメの企画を後押ししたのでは』という仮説を、Verena Maser博士論文の一次インタビューを中心に検証する。核心の因果は裏付けられなかったが、代わりに『百合ジャンル自体、2010年代後半までは商業的にまだ若く、企画が通りにくいジャンルだった』という時系列の逆説が見つかった。 | 百合, 男性不在アニメ, yuruyuri, verena-maser, madoka-magica, k-on, watanare, きらら系, 商業戦略 | 2026-08-13 |
| [リアルタイム評価が芸術のペース配分を前倒しにする ── なろうからTV・YouTube・Netflix・Twitchまで](/topics/materials/realtime-feedback-narrative-pacing-frontloading/) | なろう系の『初速依存』構造がなろう固有かメディア横断の帰結かを、TV・YouTube・TikTok・Netflix・Twitch・文学史・学術理論の8方向から検証する。査読論文が2条件フレームワークの因果を裏付ける一方、コールドオープン神話・YouTube15秒神話・Netflixデータドリブン編集神話という3つの通説がそれぞれ反証・相対化された。 | リアルタイム評価, アテンションエコノミー, ゲートキーピング, プラットフォーム経済, ペース配分, フック文化, なろう系 | 2026-08-13 |
| [代行バトルの解消パターン ── 『僕』を強くする系譜と『僕』を消す系譜](/topics/materials/daiko-battle-resolution-patterns/) | 本田透の「代行バトル」論（女性キャラが戦い、男性主人公は無力）が、その後の作品でどう解消されてきたかを2方向で辿る。「僕」自身を強くする方向（最終兵器彼女→灼眼のシャナ→Fate/stay night）と、「僕」という主語自体を消す方向（きらら系→まどか☆マギカ→ガールズ&パンツァー・リコリス・リコイル）。 | 代行バトル, honda-toru, madoka-magica, きらら系, shakugan-no-shana, fate-stay-night, saikano, girls-und-panzer, lycoris-recoil, 百合 | 2026-08-12 |
| [なろう系はなぜチート化したか ── プラットフォーム経済とテンプレ形成の年表](/topics/materials/narou-cheat-genre-platform-economy/) | なろう系（異世界転生＋チート）のテンプレが2010年代前半にどう確立したかを、プラットフォームのランキング機構という一次要因から辿る。異能バトル系ラノベの失速とタイミングが重なるジャンル疲弊説、震災後心理補償説の検証（学術的裏付けは見当たらず）まで、複数の仮説を年表と定量データで検証する。 | なろう系, shosetsuka-ni-naro, プラットフォーム経済, テンプレ, 異世界転生, mushoku-tensei, ランキング, ライトノベル | 2026-08-12 |
| [戦闘美少女の精神分析 ── ファリック・ガール論は独自論か、系譜の一部か](/topics/materials/sento-bishoujo-phallic-girl/) | 斎藤環『戦闘美少女の精神分析』のファリック・ガール概念を、東浩紀・本田透・荷宮和子ら対立する日本の批評家の議論、セーラームーンでの男性脇役化という歴史的実証、Carol Cloverの『Final Girl』論という海外の対応理論、学術的批判の4方向から検証する。 | 戦闘美少女, saito-tamaki, ファリック・ガール, オタク論, ジェンダー表象, final-girl, carol-clover, sailor-moon, azuma-hiroki, honda-toru | 2026-08-12 |
| [自制を失うと人は「動物」になる ── 変身譚の比較神話学と、完璧主義という猛獣](/topics/materials/transformation-myth-and-perfectionism/) | 変身の原因を『呪い』『亡霊』など外部に置く東西の変身譚に対し、山月記の李徴だけは原因を内面（尊大な羞恥心）に置いた。比較神話学とインポスター症候群の心理学から、この違いを読み解く。 | weretiger,werewolf,lycanthropy,comparative-mythology,transformation-myth,perfectionism,imposter-syndrome,shame,self-consciousness | 2026-08-10 |
| [技術を女性化する ── she呼びの誤解、文法性の認知効果、日本の萌え擬人化、そしてピグマリオンまで](/topics/materials/technology-feminization-anthropomorphism/) | 船を「she」と呼ぶ英語の習慣、文法性言語が物の印象を左右するというBoroditskyの研究（ただし再現性は係争中）、日本のOS-たん的な萌え擬人化文化、ピグマリオン神話とアガルマトフィリアを、擬人化の強度スペクトラムとして整理する。 | anthropomorphism, 文法性, grammatical-gender, lera-boroditsky, she呼び, os-tan, moe-anthropomorphism, ピグマリオン, アガルマトフィリア, otaku-friendly-gal | 2026-08-10 |
| [セカイ系・なろう系・オタクに優しいギャル ── 「オタクと現実」を処理する物語装置の系譜](/topics/materials/otaku-friendly-gyaru-device/) | 「オタクに優しいギャル」を、セカイ系・なろう系に続く第三の物語装置として位置づける整理。セカイ系＝セカイの縮小、なろう系＝セカイの乗り換え、オタクに優しいギャル＝現実は変えずに局所的な安全地帯だけを穿つ、という三段階の系譜として捉え、近年の「無痛コンテンツ」志向とも接続する。虚淵玄インタビューでセカイ系の時代遅れ化を裏付け。 | sekai-kei, naro-genre, otaku-friendly-gal, otaku-culture, narrative-device, painless-content, gal, validation-seeking, oshikatsu | 2026-09-13 |
| [ナラティブ・トランスポーテーション──物語に「運ばれる」とき、共感はどう変わるか](/topics/materials/narrative-transportation/) | Green & Brockのトランスポーテーション理論の骨格と測定尺度を整理し、Bal & Veltkamp (2013)の「運ばれた読者は共感が上がり、運ばれなかった読者はむしろ下がる」交互作用とスリーパー効果を軸に据える。日本の追試は読書習慣との相関を再現したが短時間曝露の因果は再現失敗——「読めば育つ」ではなく「運ばれれば変わる」という条件付きの効果。 | narrative-transportation, empathy, fiction-reading, theory-of-mind, sleeper-effect, replication, psychology | 2026-08-02 |
| [黄昏バラード・ジェネレータ ── 「切なさ」は構造として実装できるか](/topics/materials/yuming-ballad-generator-sentimentality/) | テクノエッジ連載CloseBox（松尾公也）のレポート。Claude Fable 5とのヴァイブコーディングで、初期ユーミン様式の『切なさ』を和声・メロディ・演奏タイミングの技法として構造化し、200曲を自動生成→自己採点する『黄昏バラード・ジェネレータ』を作った記録。 | ai-music, generative-music, vibe-coding, music-theory, claude, sentimentality, ai-creativity, best-of-n | 2026-07-21 |
| [名づけられない感情に言葉を与える ── Dictionary of Obscure SorrowsとEmotional Granularity](/topics/materials/naming-obscure-emotions-granularity/) | John Koenigが名づけられていない感情に造語を与え続ける『Dictionary of Obscure Sorrows』プロジェクトと、Lisa Feldman Barrettが提唱した『感情は具体的な言葉で構成される』というEmotional Granularity理論を接続する。造語（発明）だけでなく、Tim LomasのPositive Lexicography ProjectやPei-Ying Linの調査が集めた実在の他言語借用語（収集）、さらにまだどの言語にも名前がないインターネット時代の感情（未命名）まで、3つの経路を並べる。 | dictionary-of-obscure-sorrows,john-koenig,emotional-granularity,lisa-feldman-barrett,emotion,neologism,sonder,construction-of-emotion,untranslatable-words,tim-lomas,positive-lexicography,pei-ying-lin,cross-linguistic,internet-emotions | 2026-08-14 |
| [アルゴリズム的自己 ── AIは人間のアイデンティティをどう作り変えるか](/topics/materials/algorithmic-self/) | AIのフィードバックによって自己認識・内省・行為主体性が構築される『アルゴリズム的自己』論。Spotify Wrappedの事例、内省のAI委任、予測パーソナライゼーションによる選択の錯覚、ナラティブ的自己の空洞化までを整理する。 | algorithmic-self, ai-identity, introspection, digital-identity, self-tracking, narrative-agency | 2026-07-13 |
| [記憶と忘却 ── なぜ人は覚え、そしてなぜ忘れるのか](/topics/materials/memory-and-forgetting/) | 記憶（符号化・保持・想起の3段階）と忘却の基本構造をH.M.症例の研究史とともに整理。想起した記憶が一時的に不安定化し再固定化される記憶再固定化理論と、消去学習・PTSD治療への応用にも触れる。 | memory, forgetting, encoding, working-memory, long-term-memory, memory-reconsolidation, extinction-learning, ai-identity | 2026-08-23 |
| [小説を読むことの教育効果── 共感能力と「心の理論」を育てる](/topics/materials/reading-novels-education/) | 小説読書が言語能力・想像力・共感能力・心の理論・道徳的思考に与える教育効果を整理。トロント大学の研究が示す文学的小説とTheory of Mind向上の関連、読書中に運動野が活性化するという脳科学的知見に注目する。 | reading, novel, education, empathy, theory-of-mind, cognitive-development | 2026-09-03 |
| [心理的感染（Psychological Contagion）── 感情・知覚・行動はなぜ伝染するのか](/topics/materials/psychological-contagion/) | 他者の感情・知覚・行動が自分に伝染する心理的感染の理論。Houranら(2025)のCascading-Resonance Model（3層9機序）を軸に、Herrando & Constantinides(2021)のマーケティング応用研究を統合。あくび・表情模倣から集団ヒステリー・SNS炎上まで同じ機序で説明する。 | psychological-contagion, emotional-contagion, mass-hysteria, social-contagion, suggestibility, mirror-neurons, empathy | 2026-08-02 |
| [人格の同一性とテセウスの船──『同じ私』を成り立たせるもの](/topics/materials/personal-identity-theseus-ship/) | 『同じ私』であり続けるとはどういうことかを問う哲学。身体的連続性説・ロックの心理的連続性説・ヒュームのバンドル理論をテセウスの船パラドックスと組織の存続例で整理し、パーフィットのテレポーテーション・脳分裂思考実験まで辿る。 | personal-identity, philosophy, psychological-continuity, john-locke, david-hume, derek-parfit, ship-of-theseus, ai-identity | 2026-07-11 |
| [「あーし」の語源──「わたし」が崩れ落ちた先にあった言葉](/topics/materials/a-shi-etymology/) | 「わたし→あたし→あーし」の崩れの系譜と、あたいではなくあーしだけが生き残った理由をギャル語文化との接続から考察。 | ahshi, first-person, etymology, gal-slang, shibuya, japanese-language, dialect | 2026-07-05 |
| [Meishow♡Miteiについて── AIが加速させた「巻き込み型創作」の時代](/topics/materials/meishow-mitei-chain-creation/) | Meishow♡Mitei（めいみて）── AIが加速させた巻き込み型創作の時代。画像→小説→アイドルユニット→フォロワー巻き込み→Web制作の5層連鎖。AIと人間の共創、地下アイドル文化との類似性、創作主体の変容を考察する。 | ai, idol, creation, meishow-mitei, めいみて, co-creation, sns, self-produce | 2026-06-03 |
| [メモリは目的が決める ── AIエージェントにおける記憶の本質](/topics/materials/ai-memory-purpose/) | AIエージェントのメモリ論。メモリは「保持された結果」であり目的が決定する。Company Brain構想。 | ai-memory, agent, enterprise, llm, context-engineering, state-management | 2026-07-04 |
| [デフォルトモードネットワーク（DMN）──脳が何もしていないときに本当にしていること](/topics/materials/default-mode-network/) | デフォルトモードネットワーク（DMN）──脳が何もしていないときに本当にしていること。DMNの解剖学、Narrative Self理論、創造性、精神疾患との関係を総説。Volle & Beaty (2025) + Menonインタビューを統合 | neuroscience, dmn, default-mode-network, mind-wandering, creativity, consciousness, self, vinod-menon, emmanuelle-volle, roger-beaty | 2026-06-01 |
| [歩行の哲学 ── 思想家たちが「移動」に見出した自由と知性](/topics/materials/walking-philosophy/) | 歩行と思索のネットワークを概観するハブ記事。アリストテレス・ニーチェ・カント・ルソー・ソローの各記事へのリンクをまとめる。 | walking, philosophy, history, creativity, intellect, embodiment, urbanism, self-discovery, hub-article | 2026-07-04 |
| [アリストテレス ── ペリパテティック（逍遥学派）の教育と「中間の徳」](/topics/materials/aristotle-peripatetic/) | アリストテレスのペリパテティック（逍遥学派）教育と「中庸」の概念。歩行教育の3原則と、物理的ルールから倫理的概念への昇華。 | aristotle, philosophy, ancient-greece, education, peripatetic, walking, golden-mean, metaphor | 2026-06-01 |
| [ニーチェとカント ── 身体の情熱 vs 規律の散歩](/topics/materials/nietzsche-kant-walking/) | ニーチェの情熱的歩行とカントの規律的歩行の対比。1日8時間山を駆けたニーチェと、時計のように正確なルートを歩いたカント。 | friedrich-nietzsche, immanuel-kant, philosophy, contrast, walking, thinking, creativity, embodiment, discipline | 2026-06-01 |
| [ルソー『孤独な散歩者の夢想』── 迫害された思想家が自然に還るまで](/topics/materials/rousseau-reveries/) | ルソー最期の著作『孤独な散歩者の夢想』。迫害から逃れ10の「散歩」を書き連ねた、内的ナラティブとDMNの先駆的記録。第五の散歩（サン・ピエール島の小舟と「存在の感情」）を仏語原文から読み直した。 | jean-jacques-rousseau, romanticism, walking, dream, autobiography, french-literature, nature, solitude, inner-narrative, essay | 2026-10-02 |
| [ソロー『散歩（Walking）』── 歩くことは哲学である](/topics/materials/thoreau-walking/) | ソローの『散歩（Walking）』。文明から野生への抵抗としての歩行。社会という檻からの脱出。 | henry-david-thoreau, walking, wildness, nature, american-literature, essay, resistance | 2026-06-01 |
| [ギャル文化の現在地──平成ギャルから令和ギャルマインドへ](/topics/materials/gyaru-culture-current/) | 平成ギャルの全盛期から令和のギャルマインドまで。ガングロ、渋谷109、ハズしの美学、ルーズソックス復活、藤井みほなのギャル哲学、セルフラブまでを4ソースから統合。See Alsoに「あーし」の語源記事を追加。 | gyaru, ganguro, gal, fashion, culture, self-love, philosophy, showa, heisei, reiwa | 2026-07-05 |
