---
title: "Materials Index"
sidebar:
  label: "すべて見る →"
  order: 999
---


| File | Summary | Tags | Updated |
| --- | --- | --- | --- |
| [60年、誰にも見せなかった1万5000ページ ── ヘンリー・ダーガーと『非現実の王国で』](/topics/materials/henry-darger-reader-zero-realms-of-the-unreal/) | シカゴの病院清掃夫ヘンリー・ダーガーは、19歳から81歳で亡くなるまでの60年以上、誰にも見せずに1万5000ページを超える小説を書き続けた。発見はまだ存命中だったという伝記研究があり、本人は『もう遅い』と答えたとされるが、その解釈は伝記の著者自身も答えを出していない。 | henry-darger, outsider-art, in-the-realms-of-the-unreal, biography, isolation, self-reference, nathan-lerner | 2026-08-15 |
| [歓迎の言葉の裏で ── お盆をめぐる本音と、作られた伝統](/topics/materials/obon-honne-behind-welcome/) | 「孫に会えてうれしい」という定番の物語の裏で、迎える側の約4割は歓迎一辺倒ではない。2010年に企業が作った「お盆玉」という新しい伝統、そして先祖を迎える場所そのものである墓の半数近くが無縁化している現実まで、お盆の建前を支える基盤は静かに揺らいでいる。 | お盆,お盆玉,建前と本音,無縁墓,商業化,データ | 2026-08-14 |
| [お盆はむしろ、弔いを簡素にする季節だった ── データで見る変化](/topics/materials/obon-data-driven-changes/) | お盆期間は直葬が急増し、帰省しない人は6割を超え、墓じまいは特殊な選択ではなくなった。「お盆＝丁寧に弔い、家族が集う季節」という前提を、複数の調査データが静かに裏切っている。 | お盆,帰省,直葬,墓じまい,データ,現代の変化,世代間ギャップ | 2026-08-14 |
| [光る仏様とICカード ── お盆を支えるデジタル供養の現在地](/topics/materials/digital-obon-technology-columbarium/) | ICカードで自分の家の仏様だけが光る納骨堂、代理で墓参りしてVR映像を届けるサービス、死者が生前に予約したメッセージを送ってくるスマート仏壇、読経するPepper。日本の供養の現場は、過疎・後継者不足という構造問題を背景に、すでに静かにテクノロジー化している。 | お盆,デジタル供養,納骨堂,テクノロジー,多死社会,終活 | 2026-08-14 |
| [「公開処刑」は本当に模倣批判だったのか ── ZEEBRAとKjのビーフ、もう一つの見方](/topics/materials/koukai-shokei-zeebra-kj-hype-theory/) | 2002年、キングギドラの楽曲『公開処刑』でZEEBRAがDragon AshのKjを名指しでディスった事件。『模倣をやめないKjへの鉄槌』という定説に対し、リアルタイム世代の一ブロガーは『Dragon Ash叩きの世論を利用した、ギドラ再結成の話題づくりだったのでは』という別解を提示する。20年以上を経て、KjとJESSEの共作という形でこのビーフの周辺がようやく動き始めた。 | zeebra,kj,dragon-ash,公開処刑,キングギドラ,日本語ラップ,ヒップホップ,jesse,ビーフ,和解 | 2026-08-13 |
| [変わらないものを保つために、変わり続ける ── Red Bull 64Bars、3人のラッパーの継続論](/topics/materials/red-bull-64bars-continuity-and-change/) | Red Bull 64Barsに出演した3人のラッパー（OMSB・紅桜・tha BOSS）へのインタビューから、『続けること』と『変わること』をどう両立させているかを比較する。同じ問いに対して、儀式としての反復（OMSB）、一貫した人間性としての『いい男』論（紅桜）、変わらない核を保つための積極的な変化（tha BOSS）という、3つの異なる語り口が出てくる。 | ヒップホップ, ラップ, red-bull-64bars, omsb, 紅桜, tha-boss, 継続, アイデンティティ, 職人論 | 2026-08-13 |
| [百合の成熟は、男性不在アニメを後押ししたか ── 探した因果と、見つかった時差](/topics/materials/yuri-genre-male-absent-anime-reverse-causation/) | 『百合ジャンルの商業的成熟が、男性主人公不在アニメの企画を後押ししたのでは』という仮説を、Verena Maser博士論文の一次インタビューを中心に検証する。核心の因果は裏付けられなかったが、代わりに『百合ジャンル自体、2010年代後半までは商業的にまだ若く、企画が通りにくいジャンルだった』という時系列の逆説が見つかった。 | 百合, 男性不在アニメ, ゆるゆり, verena-maser, まどか☆マギカ, けいおん, わたなれ, きらら系, 商業戦略 | 2026-08-13 |
| [リアルタイム評価が芸術のペース配分を前倒しにする ── なろうからTV・YouTube・Netflix・Twitchまで](/topics/materials/realtime-feedback-narrative-pacing-frontloading/) | なろう系の『初速依存』構造がなろう固有かメディア横断の帰結かを、TV・YouTube・TikTok・Netflix・Twitch・文学史・学術理論の8方向から検証する。査読論文が2条件フレームワークの因果を裏付ける一方、コールドオープン神話・YouTube15秒神話・Netflixデータドリブン編集神話という3つの通説がそれぞれ反証・相対化された。 | リアルタイム評価, アテンションエコノミー, ゲートキーピング, プラットフォーム経済, ペース配分, フック文化, なろう系 | 2026-08-13 |
| [代行バトルの解消パターン ── 『僕』を強くする系譜と『僕』を消す系譜](/topics/materials/daiko-battle-resolution-patterns/) | 本田透の「代行バトル」論（女性キャラが戦い、男性主人公は無力）が、その後の作品でどう解消されてきたかを2方向で辿る。「僕」自身を強くする方向（最終兵器彼女→灼眼のシャナ→Fate/stay night）と、「僕」という主語自体を消す方向（きらら系→まどか☆マギカ→ガールズ&パンツァー・リコリス・リコイル）。 | 代行バトル, 本田透, まどか☆マギカ, きらら系, 灼眼のシャナ, fate-stay-night, 最終兵器彼女, ガールズ&パンツァー, リコリス・リコイル, 百合 | 2026-08-12 |
| [なろう系はなぜチート化したか ── プラットフォーム経済とテンプレ形成の年表](/topics/materials/narou-cheat-genre-platform-economy/) | なろう系（異世界転生＋チート）のテンプレが2010年代前半にどう確立したかを、プラットフォームのランキング機構という一次要因から辿る。異能バトル系ラノベの失速とタイミングが重なるジャンル疲弊説、震災後心理補償説の検証（学術的裏付けは見当たらず）まで、複数の仮説を年表と定量データで検証する。 | なろう系, 小説家になろう, プラットフォーム経済, テンプレ, 異世界転生, 無職転生, ランキング, ライトノベル | 2026-08-12 |
| [戦闘美少女の精神分析 ── ファリック・ガール論は独自論か、系譜の一部か](/topics/materials/sento-bishoujo-phallic-girl/) | 斎藤環『戦闘美少女の精神分析』のファリック・ガール概念を、東浩紀・本田透・荷宮和子ら対立する日本の批評家の議論、セーラームーンでの男性脇役化という歴史的実証、Carol Cloverの『Final Girl』論という海外の対応理論、学術的批判の4方向から検証する。 | 戦闘美少女, 斎藤環, ファリック・ガール, オタク論, ジェンダー表象, final-girl, carol-clover, セーラームーン, 東浩紀, 本田透 | 2026-08-12 |
| [自制を失うと人は「動物」になる ── 変身譚の比較神話学と、完璧主義という猛獣](/topics/materials/transformation-myth-and-perfectionism/) | 変身の原因を『呪い』『亡霊』など外部に置く東西の変身譚に対し、山月記の李徴だけは原因を内面（尊大な羞恥心）に置いた。比較神話学とインポスター症候群の心理学から、この違いを読み解く。 | weretiger,werewolf,lycanthropy,comparative-mythology,transformation-myth,perfectionism,imposter-syndrome,shame,self-consciousness | 2026-08-10 |
| [技術を女性化する ── she呼びの誤解、文法性の認知効果、日本の萌え擬人化、そしてピグマリオンまで](/topics/materials/technology-feminization-anthropomorphism/) | 船を「she」と呼ぶ英語の習慣、文法性言語が物の印象を左右するというBoroditskyの研究（ただし再現性は係争中）、日本のOS-たん的な萌え擬人化文化、ピグマリオン神話とアガルマトフィリアを、擬人化の強度スペクトラムとして整理する。 | 擬人化, 文法性, grammatical-gender, boroditsky, she呼び, os-たん, 萌え擬人化, ピグマリオン, アガルマトフィリア, オタクに優しいギャル | 2026-08-10 |
| [セカイ系・なろう系・オタクに優しいギャル ── 「オタクと現実」を処理する物語装置の系譜](/topics/materials/otaku-friendly-gyaru-device/) | 「オタクに優しいギャル」を、セカイ系・なろう系に続く第三の物語装置として位置づける整理。セカイ系＝セカイの縮小、なろう系＝セカイの乗り換え、オタクに優しいギャル＝現実は変えずに局所的な安全地帯だけを穿つ、という三段階の系譜として捉え、近年の「無痛コンテンツ」志向とも接続する。 | セカイ系, なろう系, オタクに優しいギャル, オタク文化, narrative-device, 無痛コンテンツ, ギャル, 承認欲求 | 2026-08-10 |
| [ナラティブ・トランスポーテーション──物語に「運ばれる」とき、共感はどう変わるか](/topics/materials/narrative-transportation/) | Green & Brockのトランスポーテーション理論の骨格と測定尺度を整理し、Bal & Veltkamp (2013)の「運ばれた読者は共感が上がり、運ばれなかった読者はむしろ下がる」交互作用とスリーパー効果を軸に据える。日本の追試は読書習慣との相関を再現したが短時間曝露の因果は再現失敗——「読めば育つ」ではなく「運ばれれば変わる」という条件付きの効果。 | narrative-transportation, empathy, fiction-reading, green-and-brock, theory-of-mind, sleeper-effect, replication, psychology | 2026-08-02 |
| [黄昏バラード・ジェネレータ ── 「切なさ」は構造として実装できるか](/topics/materials/yuming-ballad-generator-sentimentality/) | テクノエッジ連載CloseBox（松尾公也）のレポート。Claude Fable 5とのヴァイブコーディングで、初期ユーミン様式の『切なさ』を和声・メロディ・演奏タイミングの技法として構造化し、200曲を自動生成→自己採点する『黄昏バラード・ジェネレータ』を作った記録。 | ai-music, generative-music, vibe-coding, music-theory, claude, sentimentality, ai-creativity, best-of-n | 2026-07-21 |
| [名づけられない感情に言葉を与える ── Dictionary of Obscure SorrowsとEmotional Granularity](/topics/materials/naming-obscure-emotions-granularity/) | John Koenigが名づけられていない感情に造語を与え続ける『Dictionary of Obscure Sorrows』プロジェクトと、Lisa Feldman Barrettが提唱した『感情は具体的な言葉で構成される』というEmotional Granularity理論を接続する。造語（発明）だけでなく、Tim LomasのPositive Lexicography ProjectやPei-Ying Linの調査が集めた実在の他言語借用語（収集）、さらにまだどの言語にも名前がないインターネット時代の感情（未命名）まで、3つの経路を並べる。 | dictionary-of-obscure-sorrows,john-koenig,emotional-granularity,lisa-feldman-barrett,emotion,neologism,sonder,construction-of-emotion,untranslatable-words,tim-lomas,positive-lexicography,pei-ying-lin,cross-linguistic,internet-emotions | 2026-08-14 |
| [アルゴリズム的自己 ── AIは人間のアイデンティティをどう作り変えるか](/topics/materials/algorithmic-self/) | AIのフィードバックによって自己認識・内省・行為主体性が構築される『アルゴリズム的自己』論。Spotify Wrappedの事例、内省のAI委任、予測パーソナライゼーションによる選択の錯覚、ナラティブ的自己の空洞化までを整理する。 | algorithmic-self, ai-identity, introspection, digital-identity, self-tracking, narrative-agency | 2026-07-13 |
| [記憶と忘却 ── なぜ人は覚え、そしてなぜ忘れるのか](/topics/materials/memory-and-forgetting/) | 記憶（符号化・保持・想起の3段階）と忘却の基本構造をH.M.症例の研究史とともに整理。想起した記憶が一時的に不安定化し再固定化される記憶再固定化理論と、消去学習・PTSD治療への応用にも触れる。 | memory, forgetting, encoding, working-memory, long-term-memory, memory-reconsolidation, extinction-learning, ai-identity | 2026-07-13 |
| [小説を読むことの教育効果── 共感能力と「心の理論」を育てる](/topics/materials/reading-novels-education/) | 小説読書が言語能力・想像力・共感能力・心の理論・道徳的思考に与える教育効果を整理。トロント大学の研究が示す文学的小説とTheory of Mind向上の関連、読書中に運動野が活性化するという脳科学的知見に注目する。 | reading, novel, education, empathy, theory-of-mind, cognitive-development | 2026-08-02 |
| [心理的感染（Psychological Contagion）── 感情・知覚・行動はなぜ伝染するのか](/topics/materials/psychological-contagion/) | 他者の感情・知覚・行動が自分に伝染する心理的感染の理論。Houranら(2025)のCascading-Resonance Model（3層9機序）を軸に、Herrando & Constantinides(2021)のマーケティング応用研究を統合。あくび・表情模倣から集団ヒステリー・SNS炎上まで同じ機序で説明する。 | psychological-contagion, emotional-contagion, mass-hysteria, social-contagion, suggestibility, mirror-neurons, empathy | 2026-08-02 |
| [人格の同一性とテセウスの船──『同じ私』を成り立たせるもの](/topics/materials/personal-identity-theseus-ship/) | 『同じ私』であり続けるとはどういうことかを問う哲学。身体的連続性説・ロックの心理的連続性説・ヒュームのバンドル理論をテセウスの船パラドックスと組織の存続例で整理し、パーフィットのテレポーテーション・脳分裂思考実験まで辿る。 | personal-identity, philosophy, psychological-continuity, locke, hume, parfit, ship-of-theseus, ai-identity | 2026-07-11 |
| [「あーし」の語源──「わたし」が崩れ落ちた先にあった言葉](/topics/materials/a-shi-etymology/) | 「わたし→あたし→あーし」の崩れの系譜と、あたいではなくあーしだけが生き残った理由をギャル語文化との接続から考察。 | あーし, first-person, etymology, ギャル語, shibuya, japanese-language, dialect | 2026-07-05 |
| [Meishow♡Miteiについて── AIが加速させた「巻き込み型創作」の時代](/topics/materials/meishow-mitei-chain-creation/) | Meishow♡Mitei（めいみて）── AIが加速させた巻き込み型創作の時代。画像→小説→アイドルユニット→フォロワー巻き込み→Web制作の5層連鎖。AIと人間の共創、地下アイドル文化との類似性、創作主体の変容を考察する。 | ai, idol, creation, meishow-mitei, めいみて, co-creation, sns, self-produce | 2026-06-03 |
| [メモリは目的が決める ── AIエージェントにおける記憶の本質](/topics/materials/ai-memory-purpose/) | AIエージェントのメモリ論。メモリは「保持された結果」であり目的が決定する。Company Brain構想。 | ai-memory, agent, enterprise, llm, context-engineering, state-management | 2026-07-04 |
| [デフォルトモードネットワーク（DMN）──脳が何もしていないときに本当にしていること](/topics/materials/default-mode-network/) | デフォルトモードネットワーク（DMN）──脳が何もしていないときに本当にしていること。DMNの解剖学、Narrative Self理論、創造性、精神疾患との関係を総説。Volle & Beaty (2025) + Menonインタビューを統合 | neuroscience, dmn, default-mode-network, mind-wandering, creativity, consciousness, self, vinod-menon, emmanuelle-volle, roger-beaty | 2026-06-01 |
| [歩行の哲学 ── 思想家たちが「移動」に見出した自由と知性](/topics/materials/walking-philosophy/) | 歩行と思索のネットワークを概観するハブ記事。アリストテレス・ニーチェ・カント・ルソー・ソローの各記事へのリンクをまとめる。 | walking, 哲学, history, creativity, intellect, embodiment, urbanism, self-discovery, ハブ記事 | 2026-07-04 |
| [アリストテレス ── ペリパテティック（逍遥学派）の教育と「中間の徳」](/topics/materials/aristotle-peripatetic/) | アリストテレスのペリパテティック（逍遥学派）教育と「中庸」の概念。歩行教育の3原則と、物理的ルールから倫理的概念への昇華。 | aristotle, 哲学, ancient-greece, education, peripatetic, walking, golden-mean, metaphor | 2026-06-01 |
| [ニーチェとカント ── 身体の情熱 vs 規律の散歩](/topics/materials/nietzsche-kant-walking/) | ニーチェの情熱的歩行とカントの規律的歩行の対比。1日8時間山を駆けたニーチェと、時計のように正確なルートを歩いたカント。 | nietzsche, kant, 哲学, contrast, walking, thinking, creativity, embodiment, discipline | 2026-06-01 |
| [ルソー『散歩する孤独な人の夢』── 迫害された思想家が自然に還るまで](/topics/materials/rousseau-reveries/) | ルソー最期の著作『散歩する孤独な人の夢』。迫害から逃れ10の「散歩」を書き連ねた、内的ナラティブとDMNの先駆的記録。 | rousseau, romanticism, walking, dream, autobiography, french-literature, 自然, solitude, inner-narrative, essay | 2026-08-02 |
| [ソロー『散歩（Walking）』── 歩くことは哲学である](/topics/materials/thoreau-walking/) | ソローの『散歩（Walking）』。文明から野生への抵抗としての歩行。社会という檻からの脱出。 | thoreau, walking, wildness, 自然, american-literature, essay, resistance | 2026-06-01 |
| [ギャル文化の現在地──平成ギャルから令和ギャルマインドへ](/topics/materials/gyaru-culture-current/) | 平成ギャルの全盛期から令和のギャルマインドまで。ガングロ、渋谷109、ハズしの美学、ルーズソックス復活、藤井みほなのギャル哲学、セルフラブまでを4ソースから統合。See Alsoに「あーし」の語源記事を追加。 | gyaru, ganguro, gal, fashion, culture, self-love, philosophy, showa, heisei, reiwa | 2026-07-05 |
