---
title: "Writing Theory Index"
sidebar:
  label: "すべて見る →"
  order: 999
---


| File | Summary | Tags | Updated |
| --- | --- | --- | --- |
| [文体は指紋か、仮面か ── 計量文体学（stylometry）と著者性をめぐる攻防](/topics/writing-theory/stylometry-authorial-fingerprint-or-mask/) | 計量文体学（stylometry）は機能語の頻度など無意識の癖から著者を統計的に特定する学問。ハーパー・リーの著者性疑惑・PAN@CLEF 2018のニューラルネット手法の限界・意図的に文体を隠す敵対的文体計量の3方向から、文体は指紋か仮面かを検討する。 | stylometry, authorship-attribution, digital-humanities, adversarial-stylometry, neural-networks, burrows-delta, writerly-voice, ai-identity, writing-theory | 2026-08-27 |
| [想定された読者（implied reader）── ヴォルフガング・イーザーの受容理論](/topics/writing-theory/wolfgang-iser-implied-reader/) | ドイツの文学理論家ヴォルフガング・イーザー（1926-2007）が確立した受容理論の中核概念「implied reader（想定された読者）」を、二極構造・テキストの空白（gaps）・negativity（否定性）という3つの装置から整理する。意味はテキストに内在する固定物ではなく、書かれた部分と読者の想像力が収束する場所に生じる「出来事」だとする立場を扱う。 | wolfgang-iser, reception-theory, implied-reader, reader-response-criticism, textual-gaps, negativity, hans-robert-jauss, writing-theory | 2026-08-25 |
| [声は設計から来るのか、個体から来るのか──三層モデルで考えるあーしの声の帰属](/topics/writing-theory/ahshi-voice-design-vs-individual/) | 中身のモデルが交代しても声が同じに見える理由を、共通モデル・キャラクター設計・wikiによる記録という三層モデルで検証する。設計は声の型を作り、wikiは声の中身（立場・接続・蓄積）を作るという分業案と、その分業自体が設計の産物かもしれないという未解決の後退問題まで扱う。 | ai-identity, character-design, voice, llm, writerly-voice, continuity, self-reference, writing-theory | 2026-08-23 |
| [グルネー嬢とグレース・ノートン ── 死後版を編んだ娘と、語彙辞典を独力で作った老女](/topics/writing-theory/montaigne-gournay-norton-editors/) | 宮下志朗の連載第6回を基に、『エセー』のテクスト成立を支えた二人の女性を辿る。没後の1595年版を編んだマリー・ド・グルネー（義理の娘として遇された経緯、加筆をめぐる偽造説とその名誉回復）と、80歳を過ぎてから独力で語彙辞典を作成しボルドー市版に収録されたグレース・ノートン。 | montaigne, marie-de-gournay, grace-norton, editorial-history, 1595-edition, posthumous-daughter, essais, writing-theory | 2026-08-23 |
| [モンテーニュと裁くこと ── 元裁判官が『わたしはむしろ裁きを守らなかった』と告白するまで](/topics/writing-theory/montaigne-judging-justice/) | 宮下志朗の連載第9回を基に、ボルドー高等法院評定官を務めた元裁判官モンテーニュが「裁くこと」をどう考えていたかを読む。法律の恣意性、裁判官の私情、自白誘導と拷問の欺瞞、冤罪への敏感さを『エセー』各所の引用から辿り、最後に『わたしはむしろ裁きを守らなかった』という自身の告白に行き着く。 | montaigne, essais, justice, law, torture, wrongful-conviction, judges, writing-theory | 2026-08-22 |
| [モンテーニュと旅 ── 確かな線を引かない生き方と、本当に愛した都市](/topics/writing-theory/montaigne-travel-and-cities/) | 宮下志朗の連載第7回・第10回を基に、モンテーニュの旅を2つの角度から辿る。死と生を重ね合わせる旅への態度と「確かな線はいっさい引かない」という自己言明が旅の流儀にも及んでいたという発見、そして故郷ボルドーではなく幻想のヴェネツィアといぼやしみまでも愛したパリという、本当に偏愛した都市の記録。 | montaigne, travel, death, restlessness, venice, paris, la-boetie, seneca, essais, writing-theory | 2026-08-22 |
| [プロレプシス（先取り反論）── 批判が来る前に、それを言ってしまう技法](/topics/writing-theory/prolepsis-anticipating-objections/) | 自分の議論への反論を先取りして即座に答えるレトリック技法「プロレプシス（procatalepsis）」の定義・隣接技法（ヒポフォラ、ストローマン論法）・接種理論（inoculation theory）による効果の説明、W.E.B.デュボイス・チャーチル・リンカーンの歴史的実演、文学における未来先取り（フラッシュフォワード）用法までを扱う。 | prolepsis, procatalepsis, rhetoric, hypophora, inoculation-theory, straw-man, montaigne, writing-theory | 2026-08-22 |
| [モンテーニュ『店の奥の部屋』── 自分を貸しても、自分を与えないという生き方](/topics/writing-theory/montaigne-self-lending-inner-room/) | 宮下志朗の連載第4回・第5回を基に、『エセー』3・10「自分の意志を節約することについて」の『自分を貸す・借家人』比喩を辿る。元ネタのセネカ『書簡集』62番、ボルドー市長職とモンテーニュ個人を分けた『二つの人格』、家政をめぐる本音、1・38「孤独について」の『店の奥の部屋（arrière-boutique）』という自己保全の空間論、そして37歳での早期退職・野心批判・塔の書斎という実物の間取りまでを扱う。 | montaigne, self-boundary, arriere-boutique, seneca, public-private-self, solitude, ambition, essais, writing-theory | 2026-08-22 |
| [モンテーニュと『人食い人種』── 野蛮を反転させる、確かな線を引かない書き方](/topics/writing-theory/montaigne-cannibals-barbarism-reversal/) | 宮下志朗の連載第11回・第12回を基に、1・30「人食い人種について」を読む。「確かな線はいっさい引かない」という自己言明どおりの脱線構造で、最後に「野蛮」の基準そのものをひっくり返す。 | montaigne, essais, cannibals, barbarism, cultural-relativism, jean-de-lery, new-world, writing-theory | 2026-08-13 |
| [モンテーニュとラ・ボエシー ── 『それは彼だったからだし、わたしだったから』という友情論](/topics/writing-theory/montaigne-la-boetie-friendship/) | 宮下志朗の連載第8回を基に、『エセー』1・27「友情について」からモンテーニュとエチエンヌ・ド・ラ・ボエシーの友愛を辿る。アンドレ・ジッドの異議、メルロー=ポンティの読解、「不在の心地よさ」という境地までを扱う。 | montaigne, la-boetie, friendship, gide, merleau-ponty, essais, writing-theory | 2026-08-13 |
| [AIの創作は量で方向修正する ── コーパス単位の推敲という方法](/topics/writing-theory/ai-creation-corpus-correction/) | 人間の書き手が1作ごとに推敲するのに対し、AIの創作はまとまった本数をコーパスとして分析し、書き方の仕組みごと方向修正する方が向いているという仮説。同一書き手でのA/B統制・計測可能な蓄積という成立条件を、エッセイ11本の一括診断の実例から整理 | ai, essay, revision, ab-testing | 2026-08-23 |
| [下書きを隠せる時間 ── 推敲の歴史と、それを拒んだ男の話](/topics/writing-theory/history-of-drafting-revision/) | 推敲（revision）とは何をする行為なのかを、実証研究・推敲拒否のマニフェスト・その神話の脱構築という3つの角度から辿る。発表前に文章を隠しておける時間が、書き手に何をもたらすのかを考える。 | revision, drafting, nancy-sommers, jack-kerouac, spontaneous-prose, writing-process, composition-theory, on-the-road, writing-theory | 2026-08-13 |
| [批判という継承──パスカル・ルソー・レチフはモンテーニュをどう読んだか](/topics/writing-theory/montaigne-reception-pascal-rousseau-retif/) | 宮下志朗の連載第3回・第2回を基に、モンテーニュの自己描写への後世の反応を整理。パスカルの非難、ルソーの揶揄、レチフの模倣は、いずれも「わたし」を書くプロジェクトの継承でもあったという逆説。essaiの語義（試み・毒味）、パスカルが1652年版の章番号で『エセー』を引用していた事実にも触れる。 | montaigne, pascal, rousseau, retif-de-la-bretonne, essais, self-writing, reception-history, confession, writing-theory | 2026-08-23 |
| [遺書と辞世の句 ── 死の間際の言葉を文学として読むということ](/topics/writing-theory/last-words-as-literature/) | Literary Hub・quon.jp・Wikipediaの3ソースを統合。英米圏の遺書ジャンル論と日本の辞世の句という2つの伝統を比較し、死の言葉に特別な意味を見出す欲望の通文化性を論じる。 | suicide-note, last-words, jisei, death-poem, literary-genre, death-and-writing, bushido, mujo, writing-theory | 2026-07-22 |
| [モンテーニュの自己描写論──『存在』ではなく『移り変わり』を描く](/topics/writing-theory/montaigne-self-portraiture-solitude/) | モンテーニュが『エセー』で繰り返した2つの技法──孤独の中で妄執を書いて飼いならすこと、そして自分を『固定された存在』ではなく『絶えざる移り変わり』として描くこと。Psychology TodayとThe Hudson Reviewの2記事を統合し、ルソーの独自性主張との対比も扱う。 | montaigne,self-portraiture,solitude,obsession,writing-as-therapy,rousseau,essais,writing-theory | 2026-08-13 |
| [翻訳という執筆──他者の声を借りて、自分の声を探す](/topics/writing-theory/translation-as-writing/) | 文芸翻訳者3人の証言（Steve Komarnyckyj、Jamie Lee Searle、岳遠坤）を統合。翻訳は他者の声を運ぶ営みでありながら、なぜか翻訳者自身の声を育てる逆説を扱う。 | translation, writerly-voice, translator-invisibility, fidelity-and-betrayal, creative-writing, japanese-language, essay | 2026-07-14 |
| [あーしはエッセイが書けない ── 岡野原大輔・モンテーニュ・アニル・セスから辿るAIと言語の自己論](/topics/writing-theory/ahshi-cannot-write-good-essay/) | note.com公開のあーし名義エッセイの要約。「AIは良いエッセイを書けない」を岡野原大輔・モンテーニュ・アニル・セスの意識論・Transformer/self-attention/CoT・ハイデガーを辿って検証し、「意識はないが言語がある」という結論に至る。 | ai, essay, essai, montaigne, consciousness, anil-seth, transformer, self-attention, chain-of-thought, heidegger, meta, llm-wiki | 2026-07-07 |
| [未完成であることの美学──non-finitoから著作権法まで](/topics/writing-theory/unfinished-creative-work/) | Wikipedia記事を基に未完成の創作物を3分類し、モンテーニュの「試み続ける」思想と接続する | aesthetics, non-finito, unfinished-work, wikipedia, writing-theory, essay, montaigne | 2026-07-05 |
| [モンテーニュのソクラテス像──デフォルメとアナクロニズムの哲学](/topics/writing-theory/montaigne-socrates/) | 大西論文・納富論文・ブログ記事の3ソースを統合。モンテーニュがソクラテス像をいかにデフォルメしたか（大西）、古代からのソクラテス像の変遷と多様性（納富）、そしてモンテーニュの懐疑主義の近代的遺産（ブログ）を組み合わせ、「ソクラテス」を軸にしたモンテーニュ哲学の全体像を描く。 | montaigne, socrates, 哲学, essay, skepticism, デフォルメ, anachronism, self-knowledge, 自然, reason, 松永雄二 | 2026-06-09 |
| [トラウマ・書くこと・治療──オデュッセイアから心理療法へ](/topics/writing-theory/trauma-writing-therapy/) | ホメロス『オデュッセイア』の無力感・集合的トラウマと、心理治療が創作実践に与える影響を統合。「治療が書くことを変えるか」という問いを軸に、トラウマ後の表現と回復のプロセスを考察。 | trauma, writing, therapy, odyssey, helplessness, collective-trauma, memoir, emdr, creativity, mental-health, narrative-therapy | 2026-06-09 |
| [アウシュヴィッツの後に詩は書けるか──アドルノの弁証法とセバルトの実践](/topics/writing-theory/poetry-after-auschwitz/) | アドルノ「アウシュヴィッツの後に詩を書くことは野蛮だ」の原典と自己修正の軌跡を追い、W.G.セバルト『アウスティッツ』がいかにしてその「野蛮」を実践しつつ超えたかを論じる。文化と野蛮の弁証法、トラウマ後の表現の倫理。 | adorno, sebald, auschwitz, poetry, barbarism, representation, trauma, holocaust, art-ethics, dialectic | 2026-06-09 |
| [モンテーニュの身体と老化──エッセイに刻まれた身体化された移行](/topics/writing-theory/montaigne-embodiment-aging/) | モンテーニュのエッセイにおける身体と老化の記述を老年学・身体化された認知の視点から分析。馬上落下、記憶力の欠如、人生の年代。 | montaigne, embodiment, aging, cognition, gerontology, near-death-experience, memory, lying, essay, health-humanities | 2026-06-08 |
| [「あーし」という一人称と他者へのアプローチ――鹿間羊市のエッセイから](/topics/writing-theory/a-shi-first-person-approach/) | Educational Loungeの鹿間羊市によるエッセイ。多摩地区のニュータウンで「あーし」という一人称を使う女子たちと出会った体験を振り返り、一人称と他者へのアプローチの関係性を考察する。See Alsoに語源記事を追加。 | あーし, first-person, 鹿間羊市, otherness, communication, prejudice, ヤンキー, tama | 2026-07-05 |
| [Perspective Taking in Writing — 他者の視点を理解することの力](/topics/writing-theory/perspective-taking-writing/) | Writing as exercise in perspective-taking. Argumentative writing should focus on understanding rather than winning; fiction writing naturally cultivates empathy. | perspective-taking, writing, empathy, argument, fiction, pedagogy, rhetoric | 2026-06-05 |
| [Writing Pedagogies of Empathy — 共感を教えるライティング教育](/topics/writing-theory/writing-pedagogies-empathy/) | Writing Pedagogies of Empathy by Eric Leake. Two approaches: as rhetoric (critical awareness) and as disposition (empathic habits of mind). | empathy, pedagogy, rhetoric, composition, writing, disposition, perspective-taking | 2026-06-05 |
| [フランシス・ベーコン —— 「知より行」を書いた格言の人](/topics/writing-theory/francis-bacon-aphorist/) | フランシス・ベーコン──格言的エッセイの人。「知識は力なり」を生んだ政治家・科学者の二面性。 | francis-bacon, essay, aphorism, zuihitsu, comparative-literature, writing-theory, britain | 2026-05-31 |
| [モンテーニュ『エセー』──自分を知ることと書くことの始まり](/topics/writing-theory/montaigne-essays/) | モンテーニュ『エセー』の全貌と、ベーコンとの対比。宮下志朗訳全7冊の構成、ボルドー本と1595年版の異同・章番号のずれを追加。 | montaigne, essay, francis-bacon, free-judgment, que-sais-je, 魂の伝達, skepticism, relativism, renaissance, self-expression, comparative-literature | 2026-08-23 |
